language: haxe

haxe:
  - "3.4.4"
  - "development"

dist: trusty

sudo: false

install:
  # install awscli
  - pip install --user awscli
  - aws --version
  # install haxelibs
  - yes | haxelib install all

script:
  - haxe generate.hxml

deploy:
  provider: script
  script: haxe deploy.hxml
  on:
    branch: master
    haxe: "3.4.4"
  skip_cleanup: true